import GlobalFooter from "@/components/GlobalFooter"
import GlobalHeader from "@/components/GlobalHeader"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalHeader/>
		{children}
		<GlobalFooter/>
      </body>
    </html>
  )
}
