import { Metadata } from "next"
import GlobalFooter from "@/components/GlobalFooter"
import GlobalHeader from "@/components/GlobalHeader"

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next.js',
    template: '%s | MyLearning'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalHeader/>
		{children}
		<GlobalFooter/>
      </body>
    </html>
  )
}
